package ec.edu.espe.bank.view;

import com.mongodb.client.MongoCollection;
import ec.edu.espe.bank.controller.CheckingController;
import ec.edu.espe.bank.model.Movement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import utils.Connection;

/**
 *
 * @author Rocket Team
 */
public class FrmCheckingAccount extends javax.swing.JFrame {

    MongoCollection<Document> Movements = new Connection().obtenerDB().getCollection("SavingAccount");
    DefaultTableModel modelMovs = new DefaultTableModel();

    public FrmCheckingAccount() {
        initComponents();
        initButtons();

        modelMovs.addColumn("Name");
        modelMovs.addColumn("Account");
        modelMovs.addColumn("Date");
        modelMovs.addColumn("Type");
        modelMovs.addColumn("Amount");
        tblMovements.setModel(modelMovs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtAccountNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblInfBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDeposit = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnAdvance = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovements = new javax.swing.JTable();
        txtAvailableBalance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNameAccountHolder = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAccountNumberHolder = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnClean = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblInfAmount = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Available balance:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Checking Account");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        jLabel3.setText("Name User:");

        jLabel4.setText("Account Number:");

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 0, 102));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 102));
        btnCancel.setText("Clean");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccountNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountNumberKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Balance:");

        lblInfBalance.setForeground(new java.awt.Color(255, 0, 0));

        txtBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBalanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBalanceKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel2)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInfBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addGap(44, 44, 44)
                        .addComponent(btnCancel)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel)
                    .addComponent(jLabel13)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfBalance)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDeposit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(0, 0, 102));
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTransfer.setForeground(new java.awt.Color(0, 0, 102));
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnAdvance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdvance.setForeground(new java.awt.Color(0, 0, 102));
        btnAdvance.setText("Advance");
        btnAdvance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdvanceMouseClicked(evt);
            }
        });
        btnAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvanceActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(0, 0, 102));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Movement Type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTransfer)
                .addGap(18, 18, 18)
                .addComponent(btnReturn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit)
                    .addComponent(btnAdvance))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransfer)
                    .addComponent(btnReturn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblMovements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Account", "Date", "Type", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMovements);

        txtAvailableBalance.setEditable(false);
        txtAvailableBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableBalanceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Available Balance:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Enter the data and click on the type of movement you want to make:");

        jLabel8.setText("Name of the account holder:");

        txtNameAccountHolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameAccountHolderKeyTyped(evt);
            }
        });

        jLabel9.setText("Account Number:");

        txtAccountNumberHolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountNumberHolderKeyTyped(evt);
            }
        });

        jLabel10.setText("Amount:");

        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        btnClean.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClean.setForeground(new java.awt.Color(0, 0, 102));
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        lblInfAmount.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameAccountHolder)
                            .addComponent(txtAccountNumberHolder)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInfAmount)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClean)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNameAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAccountNumberHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean)
                    .addComponent(jLabel16)
                    .addComponent(lblInfAmount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void initButtons() {
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        btnDeposit.setEnabled(false);
        btnTransfer.setEnabled(false);
        btnAdvance.setEnabled(false);
        btnClean.setEnabled(false);
        lblInfBalance.setEnabled(false);
        txtNameAccountHolder.setEnabled(false);
        txtAccountNumberHolder.setEnabled(false);
        txtAmount.setEnabled(false);
    }

    public void deposit(float balance, float amount) {

        balance = 0;
        amount = 0;

        double sum = balance + amount;
    }

    public void withDraw(float balance, float amount) {

        balance = 0;
        amount = 0;

        double sustract = balance - amount;
    }

    public void transfer(float balance, float amount) {

        balance = 0;
        amount = 0;

        double sum = balance + amount;
    }

    public void enableFirstButtons() {
        if (!txtName.getText().isEmpty() && !txtBalance.getText().isEmpty() && !txtAccountNumber.getText().isEmpty()) {
            btnOK.setEnabled(true);
            btnCancel.setEnabled(true);
        } else {
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
        }
    }
    private void btnAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvanceActionPerformed
        txtNameAccountHolder.getText();
        txtAccountNumberHolder.getText();
        txtAmount.getText();

        Movement movement = new Movement();
        movement.setDateMovement(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        movement.setTransfer(btnTransfer.getText());

        double balance;
        double availableBalance;

        balance = Double.parseDouble(txtBalance.getText());
        double amount = Double.parseDouble(txtAmount.getText());

        availableBalance = balance - amount;
        txtAvailableBalance.setText(String.valueOf(availableBalance));

        Object mov[] = new Object[5];
        mov[0] = txtNameAccountHolder.getText();
        mov[1] = txtAccountNumberHolder.getText();
        mov[2] = movement.getDateMovement();
        mov[3] = btnTransfer.getText();
        mov[4] = txtAmount.getText();
        modelMovs.addRow(mov);

        String name = txtNameAccountHolder.getText();
        String accountNumber = txtAccountNumberHolder.getText();
        String movementType = btnTransfer.getText();

        try {
            JFrame checkingAdd = CheckingController.updateData(name, accountNumber, movementType, amount);
            Document data = new org.bson.Document();
            data.put("Name", txtNameAccountHolder.getText());
            data.put("Account Number", txtAccountNumberHolder.getText());
            data.put("Movement Type", btnTransfer.getText());
            data.put("Amount", txtAmount.getText());
            Movements.insertOne(data);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnAdvanceActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtName.setText("");
        txtAccountNumber.setText("");
        txtBalance.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        txtNameAccountHolder.getText();
        txtAccountNumberHolder.getText();
        txtAmount.getText();

        Movement movement = new Movement();
        movement.setDateMovement(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        movement.setDeposit(btnDeposit.getText());

        double balance;
        double availableBalance;

        balance = Double.parseDouble(txtBalance.getText());
        double amount = Double.parseDouble(txtAmount.getText());

        availableBalance = balance + amount;
        txtAvailableBalance.setText(String.valueOf(availableBalance));

        Object mov[] = new Object[5];
        mov[0] = txtNameAccountHolder.getText();
        mov[1] = txtAccountNumberHolder.getText();
        mov[2] = movement.getDateMovement();
        mov[3] = btnDeposit.getText();
        mov[4] = txtAmount.getText();
        modelMovs.addRow(mov);

        String name = txtNameAccountHolder.getText();
        String accountNumber = txtAccountNumberHolder.getText();
        String movementType = btnDeposit.getText();

        try {
            JFrame checkingAdd = CheckingController.updateData(name, accountNumber, movementType, amount);
            Document data = new org.bson.Document();
            data.put("Name", txtNameAccountHolder.getText());
            data.put("Account Number", txtAccountNumberHolder.getText());
            data.put("Movement Type", btnDeposit.getText());
            data.put("Amount", txtAmount.getText());
            Movements.insertOne(data);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        JOptionPane.showMessageDialog(this, "Enter data to perform some type of movement");
        btnClean.setEnabled(true);
        btnDeposit.setEnabled(true);
        btnTransfer.setEnabled(true);
        btnAdvance.setEnabled(true);
        btnClean.setEnabled(true);
        txtNameAccountHolder.setEnabled(true);
        txtAccountNumberHolder.setEnabled(true);
        txtAmount.setEnabled(true);

        txtName.setEnabled(false);
        txtBalance.setEnabled(false);
        txtAccountNumber.setEnabled(false);

        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        lblInfBalance.setText("");


    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtNameAccountHolder.setText("");
        txtAccountNumberHolder.setText("");
        txtAmount.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        txtNameAccountHolder.getText();
        txtAccountNumberHolder.getText();
        txtAmount.getText();

        Movement movement = new Movement();
        movement.setDateMovement(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        movement.setTransfer(btnTransfer.getText());

        double balance;
        double availableBalance;

        balance = Double.parseDouble(txtBalance.getText());
        double amount = Double.parseDouble(txtAmount.getText());

        availableBalance = balance - amount;
        txtAvailableBalance.setText(String.valueOf(availableBalance));

        Object mov[] = new Object[5];
        mov[0] = txtNameAccountHolder.getText();
        mov[1] = txtAccountNumberHolder.getText();
        mov[2] = movement.getDateMovement();
        mov[3] = btnTransfer.getText();
        mov[4] = txtAmount.getText();
        modelMovs.addRow(mov);

        String name = txtNameAccountHolder.getText();
        String accountNumber = txtAccountNumberHolder.getText();
        String movementType = btnTransfer.getText();

        try {
            JFrame checkingAdd = CheckingController.updateData(name, accountNumber, movementType, amount);
            Document data = new org.bson.Document();
            data.put("Name", txtNameAccountHolder.getText());
            data.put("Account Number", txtAccountNumberHolder.getText());
            data.put("Movement Type", btnTransfer.getText());
            data.put("Amount", txtAmount.getText());
            Movements.insertOne(data);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTransferActionPerformed

    private void txtAvailableBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableBalanceActionPerformed

    }//GEN-LAST:event_txtAvailableBalanceActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmAccount open = new FrmAccount();
        open.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        enableFirstButtons();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyReleased
        enableFirstButtons();

    }//GEN-LAST:event_txtBalanceKeyReleased

    private void txtAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNumberKeyReleased
        enableFirstButtons();
    }//GEN-LAST:event_txtAccountNumberKeyReleased

    private void txtAccountNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNumberKeyTyped
        char numbers = evt.getKeyChar();
        if (numbers < '0' || numbers > '9') {
            evt.consume();
        }

        if (txtAccountNumber.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR, The account number only has 10 digits");
            txtAccountNumber.setText("");
        }
    }//GEN-LAST:event_txtAccountNumberKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        char letters = evt.getKeyChar();
        if ((letters < 'a' || letters > 'z') && (letters < 'A' || letters > 'Z')) {
            evt.consume();
        }
        if (txtName.getText().length() >= 15) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR, Should not be a very long name");
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyTyped
        lblInfBalance.setText("Use the point for tenths");
    }//GEN-LAST:event_txtBalanceKeyTyped

    private void txtNameAccountHolderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameAccountHolderKeyTyped
        char letters = evt.getKeyChar();
        if ((letters < 'a' || letters > 'z') && (letters < 'A' || letters > 'Z')) {
            evt.consume();
        }
        if (txtNameAccountHolder.getText().length() >= 15) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR, Should not be a very long name");
            txtNameAccountHolder.setText("");
        }
    }//GEN-LAST:event_txtNameAccountHolderKeyTyped

    private void txtAccountNumberHolderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNumberHolderKeyTyped
        char numbers = evt.getKeyChar();
        if (numbers < '0' || numbers > '9') {
            evt.consume();
        }

        if (txtAccountNumberHolder.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR, The account number only has 10 digits");
            txtAccountNumberHolder.setText("");
        }
    }//GEN-LAST:event_txtAccountNumberHolderKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        lblInfAmount.setText("Use the point for tenths");
    }//GEN-LAST:event_txtAmountKeyTyped

    private void btnAdvanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdvanceMouseClicked
        FrmEstimateInterest open = new FrmEstimateInterest();
        open.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnAdvanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCheckingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCheckingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCheckingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCheckingAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCheckingAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvance;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblInfAmount;
    private javax.swing.JLabel lblInfBalance;
    private javax.swing.JTable tblMovements;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAccountNumberHolder;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAvailableBalance;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameAccountHolder;
    // End of variables declaration//GEN-END:variables
}
