<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
=======
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
package ec.edu.espe.smartCity.view;

import com.mongodb.client.MongoCollection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import utils.Connection;

/**
 *
 * @author Melanie
 */
public class FrmInsert extends javax.swing.JFrame {

    MongoCollection<Document> ChristmasTree = new Connection().getDB().getCollection("ChristmasTree");
    DefaultTableModel table = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    /**
     * Creates new form FrmInsert
     */
    public FrmInsert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnSmall = new javax.swing.JRadioButton();
        rbtnMedium = new javax.swing.JRadioButton();
        rbtnLarge = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbtnPine = new javax.swing.JRadioButton();
        rbtnFir = new javax.swing.JRadioButton();
        rbtnArtificial = new javax.swing.JRadioButton();
        btnInsert = new javax.swing.JButton();
<<<<<<< HEAD
=======
        btnUpdate = new javax.swing.JButton();
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insert");

        jLabel2.setText("Code");

        jLabel3.setText("Price");

        jLabel4.setText("Size");

        rbtnSmall.setText("Small");

        rbtnMedium.setText("Medium");

        rbtnLarge.setText("Large");

        jLabel5.setText("Color");

        jLabel6.setText("Type");

        rbtnPine.setText("Pine");

        rbtnFir.setText("Fir");

        rbtnArtificial.setText("Artificial");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnPine)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbtnSmall)
                                .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(txtPrice)
                                .addComponent(rbtnMedium)
                                .addComponent(rbtnLarge)
                                .addComponent(txtColor))
                            .addComponent(rbtnFir)
<<<<<<< HEAD
                            .addComponent(rbtnArtificial)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnInsert)))
                .addContainerGap(89, Short.MAX_VALUE))
=======
                            .addComponent(rbtnArtificial))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(70, 70, 70))
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtnSmall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnLarge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnPine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnArtificial)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate))
                .addContainerGap(16, Short.MAX_VALUE))
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String size = null;
        if (rbtnSmall.isSelected()) {
            size = "Small";
        } else if (rbtnMedium.isSelected()) {
            size = "Medium";
        } else if (rbtnLarge.isSelected()) {
            size = "Large";
<<<<<<< HEAD
         String type = null;
            if (rbtnPine.isSelected()) {
                size = "Pine";
            } else if (rbtnFir.isSelected()) {
                size = "Fir";
            } else if (rbtnArtificial.isSelected()) {
                size = "Artificial";

                try {
                    Document data = new Document();

                    data.put("Code", txtCode.getText());
                    data.put("Price", Float.valueOf(txtPrice.getText()));
                    data.put("Size", size);
                    data.put("Color", txtColor.getText());
                    data.put("Type", type);
                    ChristmasTree.insertOne(data);

                    JOptionPane.showMessageDialog(this, "**High School Added**");

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this, "ERROR!: " + err.getMessage());
                }
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
             * @param args the command line arguments
             */
=======
        }
        String type = null;
        if (rbtnPine.isSelected()) {
            type = "Pine tree";
        } else if (rbtnFir.isSelected()) {
            type = "Fir tree";
        } else if (rbtnArtificial.isSelected()) {
            type = "Artificial tree";
        }
        try {
            Document data = new Document();

            data.put("Code", txtCode.getText());
            data.put("Price", Float.valueOf(txtPrice.getText()));
            data.put("Size", size);
            data.put("Color", txtColor.getText());
            data.put("Type", type);
            ChristmasTree.insertOne(data);

            JOptionPane.showMessageDialog(this, "**Christmas Tree Added**");

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, "ERROR!: " + err.getMessage());
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        FrmChristmasTree frmChristmasTree = new FrmChristmasTree();
        frmChristmasTree.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
<<<<<<< HEAD
=======
    private javax.swing.JButton btnUpdate;
>>>>>>> c50923a3e00f9fd0ab967c71fc1ecc60facd57af
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbtnArtificial;
    private javax.swing.JRadioButton rbtnFir;
    private javax.swing.JRadioButton rbtnLarge;
    private javax.swing.JRadioButton rbtnMedium;
    private javax.swing.JRadioButton rbtnPine;
    private javax.swing.JRadioButton rbtnSmall;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
