/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.catering.view;

/**
 *
 * @author ASUS
 */
public class frmCateringPlanner extends javax.swing.JFrame {

    /**
     * Creates new form frmCateringPlanner
     */
    public frmCateringPlanner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCateringPlanner = new javax.swing.JMenu();
        ItmAbout = new javax.swing.JMenuItem();
        ItmExit = new javax.swing.JMenuItem();
        MenuNews = new javax.swing.JMenu();
        ItmsReservations = new javax.swing.JMenuItem();
        ItmEvents = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CATERING PLANNER");

        MenuCateringPlanner.setText("Catering Planner");

        ItmAbout.setText("About");
        ItmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmAboutActionPerformed(evt);
            }
        });
        MenuCateringPlanner.add(ItmAbout);

        ItmExit.setText("Exit");
        ItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmExitActionPerformed(evt);
            }
        });
        MenuCateringPlanner.add(ItmExit);

        jMenuBar1.add(MenuCateringPlanner);

        MenuNews.setText("New");

        ItmsReservations.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItmsReservations.setText("Reservations");
        ItmsReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmsReservationsActionPerformed(evt);
            }
        });
        MenuNews.add(ItmsReservations);

        ItmEvents.setText("Events");
        ItmEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmEventsActionPerformed(evt);
            }
        });
        MenuNews.add(ItmEvents);

        jMenuBar1.add(MenuNews);

        jMenu1.setText("Resources");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmAboutActionPerformed
    boolean alreadyDisposed = false;
    private void ItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmExitActionPerformed
      if(this.isDisplayable()){
          alreadyDisposed = true;
          this.dispose();
      }   
    }//GEN-LAST:event_ItmExitActionPerformed

    private void ItmsReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmsReservationsActionPerformed
       frmReservations FrmReservations = new frmReservations();
       FrmReservations.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ItmsReservationsActionPerformed

    private void ItmEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmEventsActionPerformed
       frmEvents FrmEvents = new frmEvents();
       FrmEvents.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ItmEventsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCateringPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCateringPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCateringPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCateringPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCateringPlanner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmAbout;
    private javax.swing.JMenuItem ItmEvents;
    private javax.swing.JMenuItem ItmExit;
    private javax.swing.JMenuItem ItmsReservations;
    private javax.swing.JMenu MenuCateringPlanner;
    private javax.swing.JMenu MenuNews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
